FROM 085170591206.dkr.ecr.us-east-1.amazonaws.com/sbt-spark-builder:latest

ARG APP_VERSION
WORKDIR /code

# Add in important dependency related files to allow for caching
ADD build.sbt /code
ADD project/build.properties /code/project/build.properties
ADD project/plugins.sbt /code/project/plugins.sbt
RUN ["sbt", "update"]

# Add in the code (i.e. the most volatile piece to leverage caching above)
ADD src/ /code/src
RUN sbt "set version := \"$APP_VERSION\"" assembly
