apiVersion: v1
kind: Pod
metadata:
  name: "es-household-retention-spark-job"
spec:
  containers:
  - name: "es-household-retention-spark-job"
    #image pull policy for local testing
    imagePullPolicy: IfNotPresent
    image: 085170591206.dkr.ecr.us-east-1.amazonaws.com/es-household-retention-spark-job:latest
    env:
      - name: CLIENT_CODE
        value: "TRAIN"
      - name: ES_HOST
        value: "exp-elasticsearch.default.svc.cluster.local"
      - name: ES_INDEX
        value: "exp_v1_1_3"
      - name: SPARK_PROCESS_BATCH_SIZE
        value: "1000"
      - name: ES_WRITE_BATCH_SIZE_BYTES
        value: "1mb"
      - name: ES_PORT
        value: "9200"
      - name: LOG_LEVEL
        value: "WARN"
 
  restartPolicy: Never

  # static config a la /values/edp/thing
  # check out common config/external dns in /charts/aurora
# spark.sparkContext.setLogLevel('WARN')
# to set the context to the dev cluster 
# kubectl config use-context kube-spantree.emp.healthgrades.io
# to set context back to local cluster
# kubectl config use-context minikube

# to run this pod 
# kubectl create -f pod.yaml 

# to follow the pod logs 
# kubectl logs --follow es-household-retention-spark-job
# to attach to the pod
# kubectl attach es-household-retention-spark-job -i
# to prematurely kill the pod
# kubectl delete -f pod.yaml

